---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - directory: "/topics/terraform/basic/aws-ec2"
    package-ecosystem: "terraform"
    schedule:
      interval: "weekly"
  - directory: "/topics/terraform/advanced/aws-three-tier"
    package-ecosystem: "terraform"
    schedule:
      interval: "weekly"
